version: "3.8"

services:
  products:
    build:
      context: ../products-ms         
      dockerfile: Dockerfile.products
    ports:
      - "3000:3000"                   
    volumes:
      - ../products-ms/database.sqlite:/app/database.sqlite
    networks:
      - backendlinktic
    restart: always                  

  inventory:
    build:
      context: ../inventory-ms
      dockerfile: Dockerfile.inventory
    ports:
      - "4000:4000"
    volumes:
      - ../inventory-ms/database.sqlite:/app/database.sqlite
    networks:
      - backendlinktic
    depends_on:
      - products                     
    restart: always

networks:
  backendlinktic:
    driver: bridge                   
