# use base img node 
FROM node:18

# directory work
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependences
RUN npm install

# copy code source
COPY . .

# expose port express
EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]
